### ISSUE TITLE
`jekyll serve` causes error, can't dev on my computer

### ISSUE THREAD

**Issue by daigofuji** [baseballhackday/baseballhackday.github.io#17]
I can't figure it out. I'm using ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
and jekyll-assets 0.10.1 is installed via bundler...
Can someone advise me? Thanks.

```
dfujiwara-mc-l:baseballhackday.github.io on source 
daigo.fujiwara$ jekyll serve
Configuration file: /Users/daigo.fujiwara/Documents/git-repos/baseballhackday.github.io/_config.yml
/usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- jekyll-assets (LoadError)
	from /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/daigo.fujiwara/Documents/git-repos/baseballhackday.github.io/source/_plugins/ext.rb:1:in `<top (required)>'
	from /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/lib/ruby/gems/2.3.0/gems/jekyll-3.0.2/lib/jekyll/plugin_manager.rb:75:in `block (2 levels) in require_plugin_files'
	from /usr/local/lib/ruby/gems/2.3.0/gems/jekyll-3.0.2/lib/jekyll/plugin_manager.rb:74:in `each'
	from /usr/local/lib/ruby/gems/2.3.0/gems/jekyll-3.0.2/lib/jekyll/plugin_manager.rb:74:in `block in require_plugin_files'
	from /usr/local/lib/ruby/gems/2.3.0/gems/jekyll-3.0.2/lib/jekyll/plugin_manager.rb:73:in `each'
	from /usr/local/lib/ruby/gems/2.3.0/gems/jekyll-3.0.2/lib/jekyll/plugin_manager.rb:73:in `require_plugin_files'
	from /usr/local/lib/ruby/gems/2.3.0/gems/jekyll-3.0.2/lib/jekyll/plugin_manager.rb:18:in `conscientious_require'
	from /usr/local/lib/ruby/gems/2.3.0/gems/jekyll-3.0.2/lib/jekyll/site.rb:97:in `setup'
	from /usr/local/lib/ruby/gems/2.3.0/gems/jekyll-3.0.2/lib/jekyll/site.rb:49:in `initialize'
	from /usr/local/lib/ruby/gems/2.3.0/gems/jekyll-3.0.2/lib/jekyll/commands/build.rb:30:in `new'
	from /usr/local/lib/ruby/gems/2.3.0/gems/jekyll-3.0.2/lib/jekyll/commands/build.rb:30:in `process'
	from /usr/local/lib/ruby/gems/2.3.0/gems/jekyll-3.0.2/lib/jekyll/commands/serve.rb:26:in `block (2 levels) in init_with_program'
	from /usr/local/lib/ruby/gems/2.3.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
	from /usr/local/lib/ruby/gems/2.3.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
	from /usr/local/lib/ruby/gems/2.3.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
	from /usr/local/lib/ruby/gems/2.3.0/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
	from /usr/local/lib/ruby/gems/2.3.0/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
	from /usr/local/lib/ruby/gems/2.3.0/gems/jekyll-3.0.2/bin/jekyll:17:in `<top (required)>'
	from /usr/local/bin/jekyll:23:in `load'
	from /usr/local/bin/jekyll:23:in `<main>'
```

**Comment by arkadyan** [comment]
@daigofuji have you tried running as `bundle exec jekyll serve`? I'm on Ruby 2.2.3 but that worked for me.

**Comment by daigofuji** [comment]
It must have been issue with an old version of bundler or something. After running `gem install bundler` it was fixed!
Thanks.
